# ~/.config/oh-my-posh/gedarufi.toml

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 4

[palette]
main-bg = "#24283b"
dark-bg = "#1a1b26"
terminal-red = "#f7768e"
pistachio-green = "#9ece6a"
terminal-green = "#73daca"
terminal-yellow = "#e0af68"
terminal-blue = "#7aa2f7"
terminal-inger = "#00adef"
terminal-inger2 = "#70D7FF"
celeste-blue = "#b4f9f8"
light-sky-blue = "#7dcfff"
terminal-white = "#c0caf5"
white-blue = "#a9b1d6"
blue-bell = "#9aa5ce"
pastal-grey = "#cfc9c2"
terminal-magenta = "#bb9af7"
terminal-orange = "#ff9e64"
blue-black = "#565f89"
terminal-black = "#414868"
t-background = "p:main-bg"

[transient_prompt]
background = "transparent"
foreground_templates = [
  "{{if gt .Code 0}}p:terminal-red{{end}}",
  "{{if eq .Code 0}}p:terminal-magenta{{end}}",
]
template = "{{if .Root}}\u26a1 {{end}}❯ "

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  background = "p:terminal-inger"
  foreground = "p:terminal-white"
  style = "powerline"
  template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
  type = "os"

    [blocks.segments.options]
    windows = "\uf179"

  [[blocks.segments]]
  background = "p:terminal-inger2"
  foreground = "p:dark-bg"
  powerline_symbol = "\ue0b0"
  style = "powerline"
  template = " {{ .UserName }} "
  type = "session"

  [[blocks.segments]]
  background = "p:main-bg"
  foreground = "p:terminal-inger2"
  powerline_symbol = "\ue0b0"
  style = "powerline"
  template = " {{ .Path }} "
  type = "path"

    [blocks.segments.options]
    folder_icon = "\uf115"
    folder_separator_icon = " \ue0b1 "
    home_icon = "\ueb06"
    style = "full"

  [[blocks.segments]]
  background = "p:terminal-green"
  background_templates = [
    "{{ if gt .Code 0 }}p:terminal-red{{ end }}"
  ]
  foreground = "p:dark-bg"
  powerline_symbol = "\ue0b0"
  style = "powerline"
  template = "{{ if gt .Code 0 }}  {{ end }}{{ if eq .Code 0 }}  {{ end }}"
  type = "status"

    [blocks.segments.options]
    always_enabled = true

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "p:terminal-yellow"
  style = "plain"
  template = " \u26a1 "
  type = "root"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground_templates = [
    "{{if gt .Code 0}}p:terminal-red{{end}}",
    "{{if eq .Code 0}}p:terminal-magenta{{end}}",
  ]
  background = "transparent"
  template = "❯"
