"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 4

[transient_prompt]
background = "transparent"
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]
template = "{{if .Root}}\u26a1 {{end}}❯ "

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  background = "#00adef"
  foreground = "#1a1b26"
  style = "powerline"
  template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}}"
  type = "os"

    [blocks.segments.options]
    windows = "\uf179"

  [[blocks.segments]]
  background = "#00adef"
  foreground = "#1a1b26"
  powerline_symbol = "\ue0b0"
  style = "powerline"
  template = "{{ .UserName }} "
  type = "session"

  [[blocks.segments]]
  background = "#24283b"
  foreground = "#a9b1d6"
  powerline_symbol = "\ue0b0"
  style = "powerline"
  template = " \ue5ff {{ .Path }} "
  type = "path"

    [blocks.segments.options]
    folder_separator_icon = "/"

  [[blocks.segments]]
  background = "#9ece6a"
  background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9e64{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f7768e{{ end }}",
    "{{ if gt .Ahead 0 }}#7dcfff{{ end }}",
    "{{ if gt .Behind 0 }}#ff9e64{{ end }}"
  ]
  foreground = "#1a1b26"
  powerline_symbol = "\ue0b0"
  style = "powerline"
  template = " {{ .HEAD }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
  type = "git"

    [blocks.segments.options]
    fetch_status = true

  [[blocks.segments]]
  background = "#73daca"
  background_templates = [
    "{{ if gt .Code 0 }}#f7768e{{ end }}"
  ]
  foreground = "#1a1b26"
  powerline_symbol = "\ue0b0"
  style = "powerline"
  template = " \uea6c "
  type = "status"

    [blocks.segments.options]
    always_enabled = true

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  background = "#f7768e"
  background_templates = [
    "{{if eq \"Charging\" .State.String}}#9ece6a{{end}}",
    "{{if eq \"Discharging\" .State.String}}#e0af68{{end}}",
    "{{if eq \"Full\" .State.String}}#7aa2f7{{end}}"
  ]
  foreground = "#1a1b26"
  invert_powerline = true
  powerline_symbol = "\ue0b2"
  style = "powerline"
  template = " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295 \ueb2d "
  type = "battery"

  [[blocks.segments]]
  background = "#7aa2f7"
  foreground = "#1a1b26"
  invert_powerline = true
  powerline_symbol = "\ue0b2"
  style = "powerline"
  template = " \ue235 {{ .Venv }} "
  type = "python"

    [blocks.segments.options]
    display_mode = "context"
    fetch_virtual_env = true

  [[blocks.segments]]
  background = "#24283b"
  foreground = "#a9b1d6"
  invert_powerline = true
  powerline_symbol = "\ue0b2"
  style = "powerline"
  template = "<#a9b1d6> \ue641 </>{{ .CurrentDate | date .Format }} "
  type = "time"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#e0af68"
  style = "plain"
  template = " \u26a1 "
  type = "root"

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'
